/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TicTacAvax__factory } from "./TicTacAvax__factory";
export { TicTacAvaxCross__factory } from "./TicTacAvaxCross__factory";
